[package]
name = "plugin-base"
version = "0.1.0"
edition = "2021"

[dependencies]
abi_stable = "0.10.4"
konst = "0.2"
libloading = "0.7"
log = "0.4"
once_cell = "1.13.0"
pretty_env_logger = "0.4.0"
semver = "1.0"
thiserror = "1.0"
